stages:
  - pull_dev

deploy-dev:
  stage: pull_dev
  tags:
    - pull_dev
  only:
    - master
  when: always
  script:
    - cd /var/www/www-root/data/www/$SITE_NAME/
    - rm -rf build
    - git reset --hard HEAD
    - git pull origin master
    - npm run build
